// Categories list
export const categories = [
  "Advocacia",
  "Cabeleireiro",
  "Construção",
  "Cozinheiro",
  "Desenvolvedor",
  "Eletricista",
  "Encanador",
  "Fisioterapia",
  "Fotógrafo",
  "Jardinagem",
  "Limpeza",
  "Manicure",
  "Marcenaria",
  "Mecânica",
  "Musica",
  "Personal",
  "Saude",
];
